config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  resources :users, only: %i[new create]
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to do that"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    message = current_user.messages.build(message_params)
    ActionCable.server.broadcast 'chatroom_channel', mod_message: message_render(message) if message.save
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]
  def new; end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'Logged in successfully'
      redirect_to root_path
    else
      flash.now[:error] = "Couldn't login at this time. Please check your credentials."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Successfully logged out'
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = 'You are already logged in'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Signup successful! Welcome, #{@user.username}!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="blue circular users icon"></i>
  Chatroom
</h2>

<div class="ui grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <% if @messages.any? %>
            <%= render @messages %>
          <% end %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: { class: 'ui reply form', role: 'form' }, url: message_path, remote: true) do |f| %>
          <div class="ui fluid action input">
            <%= f.text_field :body, placeholder: 'Type your message...' %>
            <%= f.button '<i class="paper plane icon"></i>'.html_safe, class: 'ui button green' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui middle aligned selection list">
          <div class="item">
            <i class="user circle icon"></i>
            <div class="content">
              <div class="header">Helen</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="ui <%= type %> message">
    <i class="close icon"></i>
    <div class="header">
      <%= msg %>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="ui large inverted menu" id="square-menu">
  <div class="ui container">
    <%= link_to 'Chatroom', root_path,  class: 'active item' %>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to 'Log out', logout_path, class: 'item', method: :delete %>
          <% else %>
            <%= link_to 'Log in', login_path,  class: 'item' %>
          <% end %>
        </div>
      </div>
      <% if !logged_in? %>
        <div class="item">
          <%= link_to 'Sign up', signup_path,  class: 'ui primary button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="ui error message">
    <i class="close icon"></i>
    <div class="header">
      Error!
    </div>
    <% obj.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="ui container">
  <h2 class="ui center aligned icon header">
    <i class="circular signup blue icon"></i>
    Sign Up
  </h2>
  <%= render 'shared/errors', obj: @user %>
  <%= form_with(model: @user, class: 'ui form', local: true) do |f| %>
    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username, placeholder: 'Username' %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, placeholder: 'Password' %>
    </div>
    <div class="ui fluid">
      <%= f.button 'Submit', class: 'ui button green' %>
    </div>
  <% end %>
</div>